### PR TITLE
added NATURAL JOIN types

### PR DESCRIPTION
**Pull request by jvyyuie**
according to PR #5239, remove STRAIGHT_JOIN types, rewrite code to support NATURAL JOIN types.

### CODE REVIEW

**Comment by narfbg** [comment]
Not following our [styleguide](https://codeigniter.com/userguide3/general/styleguide.html).

Also, you're not supposed to add unnecessary stuff (STRAIGHT_JOIN) in one commit only to remove it in another.

**Comment by jvyyuie** [comment]
I read styleguide and find my patch's mistake:

`$natural_join = FALSE;`

should be:

`$_natural_join = FALSE;`

have there any other incorrects?

**Comment by narfbg** [comment]
No, the variable name is fine. The problem is with spaces around parentheses.

**Comment by jvyyuie** [comment]
thank you

**Pull request closed without merging**
