### PR TITLE
Load Migrations On Demand

### PR DESCRIPTION
**Pull request by ftwbzhao**
Always `include_once` all migration files （：Not based on valid version

```php
<?php
# $this->migration->version(999);
for($i=1; $i < 999; $i++) {
    include_once($file.'.php');
}
?>
```
---
https://robert.accettura.com/blog/2011/06/11/phps-include_once-is-insanely-expensive/

### CODE REVIEW

**Comment by narfbg** [comment]
That's the opposite of "on demand".

**Comment by ftwbzhao** [comment]
@narfbg 

```php
<?php
// if $target_version == 999 ($current_version = 998
$this->migration->version(999);
//include_once 998 times invalid file (: You Says That's the opposite of "on demand".
?>
```

**Comment by ftwbzhao** [comment]
Waiting for your reply :airplane:

**Comment by ftwbzhao** [comment]
Guys..  - explain.

**Comment by narfbg** [comment]
Don't ping me every few hours, it's annoying. And explain yourself first.

**Comment by ftwbzhao** [comment]
Code is explanation. 

When  $target_version = 999 ($current_version = 998

Use ``$this->migration->version(999);``

Do ``incluce_once`` 998 times invalid migration files.

**Comment by narfbg** [comment]
No, this is not an explanation - I can interpret that "explanation" in at least 5 different ways.

**Pull request closed without merging**
