### PR TITLE
Update user agent for Edge browser

### PR DESCRIPTION
**Pull request by blasto333**
Edge is no longer called Sparten.

### CODE REVIEW

**Comment by blasto333** [comment]
Closed as not needed

**Comment by ezequielprieto** [comment]
@blasto333 why this PR is not needed?

**Comment by blasto333** [comment]
Edge is no longer called Sparten.

**Comment by blasto333** [comment]
I don’t recall why

**Comment by blasto333** [comment]
(It was 2 years ago)

**Comment by ezequielprieto** [comment]
The last version of CI3 (3.1.8) still having Spartan in the conf.
I have updated it in my project, and search for issues/pr of this, and I found this fix but closed not merged.

**Pull request closed without merging**
