### PR TITLE
GitAttributes file to clean up composer installs

### PR DESCRIPTION
**Pull request by lonnieezell**
This basically just removes a number of development-only files (like the user guide source and our tests) from any installs made through composer with the --prefer-dist flag set. 

Helps create a faster install with less unnecessary files to new projects.

### CODE REVIEW

**Comment by narfbg** [comment]
Not sure about readme.rst and tests/codeigniter/ ... the whole tests/ directory is kinda useless without the latter.

Speaking of directories ... can we not use the word "folders" please? :)

**Comment by lonnieezell** [comment]
My main reason for removing the /codeigniter folder and leaving the rest is that I thought the mocks **directory** :) would be helpful for people developing their applications to have, but they didn't necessarily need all of our tests in their application. 

And I don't have a strong opinion one way or the other about the readme file so I'm fine keeping that. 

Let me know final consensus on the tests (which I've just been reading through comments when Symfony went through this a while back and the opinions are definitely mixed) and I'll fix it up.

**Comment by narfbg** [comment]
Oh, I thought the readme files was also ignored ... should look more carefully.

Still unsure about the tests though.

**Comment by lonnieezell** [comment]
As for tests - I guess it comes down to use-case. When we pull down a copy of the repo to start a new project with, do we need CI's tests? On one hand, it can be helpful to look at the existing tests for a reference, but you're not typically going to want to run CI's test suite whenever you run your own tests. 

If people want to ensure they get the tests, which I think would be in the minority, then they can always do a git clone, or use `--prefer-source`  with a composer install.

Obviously, I don't think they need to be in there but don't have a strong opinion either way. I can always add some docs that specify how to do both? 

@jim-parry @benedmunds What do you guys think on this one?

**Comment by benedmunds** [comment]
I'd vote for not including the tests.

**Pull request merged**
