### PR TITLE
When using post_controller_constructor hook - Undefined variable: _SESSI...

### PR DESCRIPTION
**Pull request by alexvandervegt**
...ON

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined variable: _SESSION</p>
<p>Filename: Session/Session.php</p>
<p>Line Number: 730</p>

### CODE REVIEW

**Comment by narfbg** [comment]
The error means that you've already unset these variables, but you didn't unmark them as temp/flash data. So why didn't you do that?

**Comment by alexvandervegt** [comment]
Please explain?

Also i think its always wise to check if a variable exists before unsetting it.

**Comment by narfbg** [comment]
The code that you're changing simply unsets variables that were previously marked as 'tempdata' or 'flashdata'. These markers wouldn't exist if you didn't create them via `set_flashdata()`, `set_tempdata()` or `mark_as_temp()`, `mark_as_flash()`.
Therefore, if the `unset()` call is reached for them *and* the actual variables don't exist in `$_SESSION`, that means that you've marked them as flash/temp data, but you've manually unset them without `unset_flashdata()`, `unset_tempdata()` or `unmark_flashdata()`, `unmark_tempdata()`, like this:

    $this->session->set_flashdata('foo', 'bar');
    unset($_SESSION['foo']);
    // next request will try to unset($_SESSION['foo']) again

So, wise to check for that - sure, but it currently shows a logical error in your code, so in fact the error message is helping you.

**Comment by alexvandervegt** [comment]
This is not done in the code. I just updated my system from the V3 Beta to V3 RC2 before i was using the buildin native session driver, this is not available anymore so i switched to the files driver.

And now this error appears, also i get a lot empty sessions when using the files system. So i switched back to the beta version again.

Hope you guys can do something with this feedback and update the session library to a stable one before a releasing a stable version.

**Comment by narfbg** [comment]
It is quite stable, but if you've depended on some specific behavior of the "native" driver, it may not exist with the new library.

One thing I can tell you for sure is that you certainly *are* manually deleting data that's been previously set as flashdata/userdata ... even if not with the exact same code I showed. It's simply impossible to get these error messages otherwise.

**Comment by alexvandervegt** [comment]
Its working now indeed, thanks for your replies :)

**Pull request closed without merging**
