### PR TITLE
Create Add Foreign Key Function

### PR DESCRIPTION
**Pull request by EpicKris**
Created `CI_DB_forge->add_foreign_key()` function and added documentation to user guide.

### CODE REVIEW

**Comment by EpicKris** [comment]
Slightly different implementation of #4275 to keep inline with existing `CI_DB_forge->add_key()` functionality.

**Comment by steve-goodwin** [comment]
Good work on this @EpicKris , hopefully it'll be merged soon :)

**Comment by EpicKris** [comment]
@narfbg Could you review this pull request and let me know if I should make any changes? Thanks!

**Comment by narfbg** [comment]
Did you not see my comment on #4275?

**Comment by EpicKris** [comment]
@narfbg Sorry, but I don't understand why this would only work for MySQL and not other database drivers?

**Comment by narfbg** [comment]
Because I'm yet to see a query other than very, very basic SELECT or DELETE to work across all databases. You just can't assume what works on MySQL will work for everything else ... asking "why wouldn't it" isn't serious.

Obviously, nobody has all of them in order to test, but you can at least consult different documentations to confirm it.

**Comment by EpicKris** [comment]
I'll test this with different database drivers and work out the differences, almost certain this will work for MySQL, PostgreSQL, and Microsoft SQL though.

**Comment by narfbg** [comment]
Those are only 3 out of ~10 ... and I'm pretty sure it doesn't work *out of the box* on SQLite.

**Comment by EpicKris** [comment]
@narfbg What if a database doesn't support foreign keys?

**Comment by narfbg** [comment]
Well then it obviously will fail, but it has to fail gracefully, not by virtue of the query just refusing to execute. :)

**Comment by steve-goodwin** [comment]
@EpicKris Yeah I can put some time aside to review documentation on this to see where it will fail, although re-factoring bits of code may take me longer as i'm also a little stacked at the moment though. This is a feature I need in pretty much every project though so willing to invest time into getting this into an acceptable state for a release candidate

**Comment by EpicKris** [comment]
@steve-goodwin Likewise, I'd like to get this in as soon as possible as I'd like to use it for a school project.

**Comment by EpicKris** [comment]
@steve-goodwin I'm going to start having more time on my hands, so will look into this, I also want a way of creating and deleting foreign keys independently of creating a table, deleting foreign keys may be required for downgrading migrations.

**Comment by weblogics** [comment]
@EpicKris - sorry I've been flat out on other projects, had a look through your commits and looking good. What's left to get this feature complete and passing?

**Comment by steve-goodwin** [comment]
@EpicKris - sorry I've been flat out on other projects, had a look through your commits and looking good. What's left to get this feature complete and passing?

**Comment by EpicKris** [comment]
@steve-goodwin, I've also been flat out busy with my new job, obviously the build is failing at the moment, so that needs checking out, and I'd like a way to be able to add and drop foreign keys independently of creating a table (adding and dropping foreign keys may be required for migrations, etc…), and then each database driver needs to be checked for compatibility and updated accordingly.

**Pull request closed without merging**
