### PR TITLE
Added code in CI_model to connect datbase table.

### PR DESCRIPTION
**Pull request by sagarkaurav**
Signed-off-by: sagar <sagar.kaurav@gmail.com>

### CODE REVIEW

**Comment by sagarkaurav** [comment]
@narfbg whats wrong with the idea.

**Comment by narfbg** [comment]
Pretty much everything.

**Comment by sagarkaurav** [comment]
@narfbg why can't we add basic database query code in our model class that we uses in our every project.

**Comment by gxgpet** [comment]
@sagarkaurav if you want to share with us your ideas regarding custom "basic query code", you should use the CI forums and not make a PR about it.

**Comment by sagarkaurav** [comment]
@gxgpet okk i want to add rails active record like feature in CI model.

**Comment by pfote** [comment]
there is so much wrong in your attempt that i wouldnt know where to 
start explaining

**Pull request closed without merging**
