### PR TITLE
Autoload Driver Object Names

### PR DESCRIPTION
**Pull request by EpicKris**
Updated loader to autoload drivers with object names the same as autoloading libraries.

### CODE REVIEW

**Comment by narfbg** [comment]
What's the point? Only cache uses this.

**Comment by EpicKris** [comment]
I'm using a package that has a name conflict with one of my controllers which means I'm unable to use the driver from that package.

**Comment by narfbg** [comment]
What package?

**Comment by EpicKris** [comment]
It's an internal package used across several projects and clients.

**Comment by narfbg** [comment]
You've actually developed a package based on CI_Driver? You're probably one of 5 people to ever want to do that. :)

Seriously, I'd rather discourage CI_Driver usage and this enhancement would be the opposite of that. If CI_Cache didn't use it, it would've been gone by now.

**Comment by EpicKris** [comment]
Yes, I've actually developed 2 driver libraries; one for authentication, and one for storage which works with the local file system, Amazon Web Services, etc…

Why would you discourage `CI_Driver` usage? It seems like a good concept to me?

**Comment by narfbg** [comment]
Libraries using adapters for different platforms is a good concept, `CI_Driver` is not that good of a concept. :)

It puts more limits on you than it helps and you don't really need a library called "Driver" to write libraries that have drivers/adapters. It's also largely undocumented and hard to understand - even I don't know exactly how it works, I'm impressed you've managed to put it into use.

**Comment by EpicKris** [comment]
I suppose I always just thought of drivers similar to the database library and use it in much similar way too which is different to what I think drivers were intended for, but it works. I could show you an example if you'd like?

**Comment by narfbg** [comment]
No, I don't really care to see it. You know what? I don't really care that much about this either, so I'll merge it.

**Comment by narfbg** [comment]
Or rather, I'll merge it after you fix the syntax error on line 699. Please don't submit patches that you didn't test ...

**Comment by narfbg** [comment]
Please leave a comment next time, commits don't issue notifications.

**Comment by EpicKris** [comment]
Sorry, didn't realise, thanks for merging.

**Pull request merged**
