### PR TITLE
"Named" callables; i.e. array('name' => $callable)

### PR DESCRIPTION
**Pull request by b1tc0re**

### CODE REVIEW

**Comment by narfbg** [comment]
Named callables what?

**Comment by b1tc0re** [comment]
I do not speak English well. I will make an example for 10 min and show.

**Comment by b1tc0re** [comment]
rules **required** should be checked first and then all the rest.
Send form but do not fill in the field. To check the rule **required** 
https://dev.dilexy.ru/

**Comment by b1tc0re** [comment]
Maybe need change 
`return array_merge($callbacks, $new_rules);`
to
`return array_merge($new_rules, $callbacks);`

**Comment by narfbg** [comment]
No, callbacks do come before required.

**Pull request closed without merging**
