### PR TITLE
Changes in CI_DB_query_builder and CI_DB_result

### PR DESCRIPTION
**Pull request by lubo1998**
Hi, I have done some changes, which I hope will be useful for the project.

- Added custom key option in result_array - I know that I have duplicated the loops, but that is from optimization purposes. Better first do the check and then iterate, than do the check on each iteration.
- Added possibility to use where and or_where with a single field name and array of values which will produce "$field = $value" or "$field IN ($value1, $value2 [, ...$value2])".

### CODE REVIEW

**Comment by gxgpet** [comment]
For the custom key option:

1. There are very few use cases for this in the wild... I don't see how you take it as a general case feature
2. It won't work if the `$key_column_name` column will have duplicate values
3. This effect can be easily achieved by the following one-liner: `array_column($array_result, NULL, $key_column_name)`

For the second proposal:

I'm not sure if I get it right, but you have `$this->db->or_where_in()` and `$this->db->where_in()`... Isn't this what are you looking for?

**Comment by lubo1998** [comment]
> For the custom key option:
> 
>     1. There are very few use cases for this in the wild... I don't see how you take it as a general case feature
> 
>     2. It won't work if the `$key_column_name` column will have duplicate values
> 
>     3. This effect can be easily achieved by the following one-liner: `array_column($array_result, NULL, $key_column_name)`
> 
> 
> For the second proposal:
> 
> I'm not sure if I get it right, but you have `$this->db->or_where_in()` and `$this->db->where_in()`... Isn't this what are you looking for?

For the custom key option:
1. I thought this will be useful since there is a PDO fetching style PDO::FETCH_KEY_PAIR where a column can be chosen for a key.
2. Yes, it is really possible to occur collision with the keys, but I trigger an error if this happen. The feature should be used responsibly.
3. I know there are a lot of ways to achieve this affect, but all of them include addition array loops. array_column iterate over the array too.

For the second proposal:
My idea was to use $this->db->where() and $this->db->or_where() regardless of the parameter type I pass as a value/s (array or int/string).

**Comment by gxgpet** [comment]
Well, why trigger an error? Why not override with the last duplicate value? Why not keep only the first value? All of these assumptions of how it could work will lead to numerous "this feature doesn't work as I want/expect" bug reports and it won't make everyone happy.

```
The feature should be used responsibly.
```

Never expect this from a user.

For the second improvement, it looks like this was addressed previously in #4910.

**Comment by narfbg** [comment]
In addition to @gxgpet's comments, see also #429.

**Comment by lubo1998** [comment]
> In addition to @gxgpet's comments, see also #429.

Actually [**array_column** also loops through the array](https://github.com/php/php-src/blob/b3c5b8cf2485ea99eede9bfa245d26fdb4eeb6c3/ext/standard/array.c#L4067), which are extra iterations. So, I don't think that actually **array_column** solves the problem, but if you have taken your decision, ok.

**Pull request closed without merging**
