### PR TITLE
Do not fail if the array pointer is after the element

### PR DESCRIPTION
**Pull request by vlakoff**
We should not assume the passed array has its pointer set to the first element.

### CODE REVIEW

**Comment by narfbg** [comment]
Can just replace the `current()` call with `reset()` and move it before the `key()` one. :)

**Comment by vlakoff** [comment]
Nope, because you're overwriting `$filename` ;)

**Comment by narfbg** [comment]
Eh ... you're right.

And every other solution is a dead end because PHP 7 somehow managed to be worse than PHP 5 in this case. :(

**Comment by gxgpet** [comment]
Since I made some submissions in this area (Download helper) as well, you might want to check the above lines from `reset()` :)

```
if (count($filename) !== 1)
{
	return;
}
```

**Comment by narfbg** [comment]
Single count array doesn't mean its array pointer can't be moved, which is why I hate this even more.

**Comment by gxgpet** [comment]
Oh, yeah, you are right here. I didn't see it in a procedural way of thinking.

**Pull request merged**
