### PR TITLE
Fix errors/cli/error_php.php output

### PR DESCRIPTION
**Pull request by kenjis**
Before:
~~~
$ php index.php 

Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.php on line 24

Call Stack:
    0.0053     228344   1. {main}() /Users/kenji/work/codeigniter/CodeIgniter/index.php:0
    0.0183     233128   2. require_once('/Users/kenji/work/codeigniter/CodeIgniter/system/core/CodeIgniter.php') /Users/kenji/work/codeigniter/CodeIgniter/index.php:292


A PHP Error was encountered

Severity: Parsing ErrorMessage:  syntax error, unexpected '$this' (T_VARIABLE)Filename: /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.phpLine Number: 24

Backtrace:
			
			
			
			
$ 
~~~

After:
~~~
$ php index.php 

Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.php on line 24

Call Stack:
    0.0102     228344   1. {main}() /Users/kenji/work/codeigniter/CodeIgniter/index.php:0
    0.0282     233128   2. require_once('/Users/kenji/work/codeigniter/CodeIgniter/system/core/CodeIgniter.php') /Users/kenji/work/codeigniter/CodeIgniter/index.php:292


A PHP Error was encountered

Severity: Parsing Error
Message:  syntax error, unexpected '$this' (T_VARIABLE)
Filename: /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.php
Line Number: 24

Backtrace:

$ 
~~~

### CODE REVIEW

**Comment by narfbg** [comment]
Weird ... there are obviously newline characters following each closing PHP tag, I can't even think of a reason why they could be ignored.

Anyway, I'll merge this, but please revert back the indentation levels on the PHP code.

**Comment by kenjis** [comment]
Newline character following each closing PHP tag is removed. It is PHP's specification.

~~~
$ cat test.php 
abc
<?php echo 'def'; ?>
ghi
$ php test.php 
abc
defghi
~~~

>  A linefeed that follows immediately after a closing ?> will be removed by PHP. 
http://php.net/manual/en/tutorial.firstpage.php

**Comment by kenjis** [comment]
> please revert back the indentation levels on the PHP code.

Indentation outside of PHP tag is outputed. So it will change indentation of output.

**Comment by narfbg** [comment]
OK ... so open the PHP tag at the start of the line and indent inside it ... :)

**Pull request merged**
