### PR TITLE
Update DB_result.php

### PR DESCRIPTION
**Pull request by basit-adhi**
Adding public variable $dropdown_result_array (Dropdown Result Array, use @form_dropdown)
Adding public result_dropdown(), row_dropdown_array(), unbuffered_row()
Changing some function to accomodate  $dropdown_result_array: num_rows(), result(), row()

### CODE REVIEW

**Comment by narfbg** [comment]
Even if it was a desirable feature (which it isn't), this is a classic SRP violation.

**Comment by basit-adhi** [comment]
Any suggestion? A new library?

**Comment by narfbg** [comment]
A suggestion for what? How to do this in your apps? That's up to you, it just doesn't belong in CI core.

**Comment by basit-adhi** [comment]
Ok, sorry for that. I make my own application/libraries then. Thank you

**Pull request closed without merging**
