### PR TITLE
correction on delete() return value

### PR DESCRIPTION
**Pull request by avenirer**
If no row was deleted the delete() method returned TRUE. This way we only return TRUE if at least a row was deleted.

### CODE REVIEW

**Comment by narfbg** [comment]
In SQL, that doesn't make sense. TRUE is a success, FALSE is a failure ... not finding a row is not a failure.

**Comment by avenirer** [comment]
It is a failure if you want to delete something that is not there. If there is no row deleted when you asked to delete a row, then that it is a failure.

**Comment by narfbg** [comment]
No, it's not. If it was, the query itself would trigger an error.

**Comment by avenirer** [comment]
if in the model you try:

if($this->db->delete('table', array('id'=>$nonexistent_id))
{
echo 'ok';
}
else
{
echo 'false';
}

...it will echo 'true' even if that row doesn't exist and, hence, is not deleted.

**Comment by kakysha** [comment]
Builder methods return value is to indicate the success of query execution. FALSE means that something is wrong on the way to db engine as it can not execute your query. 0 affected rows means SUCCESS of query execution, that's is why it return TRUE. Affected_rows() designed specially to use in your models, use it manually.

**Comment by avenirer** [comment]
@kakysha you may be right... but is not reasonable to say that is a success somehing that is not done. Thank you for explanation.

**Pull request closed without merging**
