### PR TITLE
Update CodeIgniter.php

### PR DESCRIPTION
**Pull request by Everterstraat**
Added FCPATH to search for on $config['composer_autoload']

### CODE REVIEW

**Comment by georgexsh** [comment]
agree with this change, but the commit message needs more detail IMO

**Comment by mwhitneysdsu** [comment]
If you want it to look in `FCPATH.'vendor/autoload.php'`, then set `$config['composer_autoload'] = FCPATH.'vendor/autoload.php';` instead of `$config['composer_autoload'] = TRUE;`...

**Comment by Everterstraat** [comment]
It's possible that way @mwhitneysdsu but why make it harder than needed?!

**Comment by mwhitneysdsu** [comment]
It's just behaving as documented. If you want to change that behavior, you should also update the comment that describes the behavior in the config file.

I don't really care either way, because setting the variable to the path would probably still be faster than setting it to `TRUE` and having it check multiple directories for the file.

**Comment by narfbg** [comment]
Because "easier" doesn't mean "correct".

[Stop](https://github.com/bcit-ci/CodeIgniter/pull/3636) [requesting](https://github.com/bcit-ci/CodeIgniter/issues/4197) [this](https://github.com/bcit-ci/CodeIgniter/pull/4701)! I don't care if a thousand PRs suggest it, it won't be merged.

**Pull request closed without merging**
