### PR TITLE
Comma before "and" grammar fix

### PR DESCRIPTION
**Pull request by morlo1**
Comma is usually not being used before "and"

### CODE REVIEW

**Comment by Tpojka** [comment]
It's called [Oxford comma](https://en.wikipedia.org/wiki/Serial_comma).

**Comment by jim-parry** [comment]
CodeIgniter is not trying to follow "Oxford English".
The closest would be "American English", as an international web convention.
The closest reference I can find is https://www.grammarly.com/blog/comma/, which suggests that such a comma is optional, and debatable, regardless of the "convention" one is adhering to.
This feels a bit too picky to get excited about!

**Comment by Tpojka** [comment]
@jim-parry If answered to me, I was just pointing that it is not inappropriate how it was already written but rather as you say more debatable should use or shouldn't. I wasn't referencing to Oxford grammar rules per se to be used in CodeIgniter. Btw. thanks for link. :)

**Comment by jim-parry** [comment]
@Tpojka Not to worry. My comment was directed more at the original poster, and explaining why the PR was not accepted.

**Pull request closed without merging**
