### PR TITLE
travis: bash cleanup

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by narfbg** [comment]
... look at the build for this PR.

**Comment by TomasVotruba** [comment]
What does closing mean?

**Comment by narfbg** [comment]
Why do you want to change it at all?

**Comment by TomasVotruba** [comment]
Better readability.

**Comment by narfbg** [comment]
I don't see much point in that for 4 lines in a bash script that's only used for tests. It's not like it's unreadable and barely anyone needs to look at it anyway.

**Comment by TomasVotruba** [comment]
I see

**Pull request closed without merging**
