### PR TITLE
Fix session crashes with UTF-8 characters

### PR DESCRIPTION
**Pull request by fubbyb**
Bug fix: endless for loop when tryinig read session data from file with UTF-8 characters.

### CODE REVIEW

**Comment by narfbg** [comment]
What's your `mbstring.func_overload` ini value?

**Comment by fubbyb** [comment]
My mbstring.func_overload set to "2". But my hosting provider doesn't allow to change this value separately for each site. So, one little change allow CI works fine with any func_overload. One more question is why you doesn't use file_get_contents function?

**Comment by gxgpet** [comment]
The two main reasons that `file_get_contents` is not used on file session driver are that (1) a file handle is required to be mainly open during a request as a class member and (2) file locking mechanism.

**Comment by narfbg** [comment]
I asked that to confirm my suspicion that mbstring is causing the issue, as `feof()` is a work-around here and renders a lot of the other logic useless. I've got another solution in mind ...

But if this is a configuration set by your hosting provider - I suggest that you switch away from them as soon as possible.

**Comment by fubbyb** [comment]
In my project I totally rewrite this part of code:
`$session_data = '';
$length = filesize($this->_file_path.$session_id);

while (!feof($this->_file_handle)) 
{
	$position = ftell($this->_file_handle);
	if (($buffer = fread($this->_file_handle, $length - $position + 1)) === FALSE) break;
	
	$session_data .= $buffer;
}`

**Pull request closed without merging**
