### PR TITLE
FIX: Fixes dynamic property deprecation error

### LINKED ISSUE #6192: Creation of dynamic property CI_URI::$config is deprecated
A stackoverflow question a user had sent me on the path of discovering why this was happening and noticed it wasn't patched in any branch or tag yet.

https://github.com/bcit-ci/CodeIgniter/blob/3.1.13/system/core/URI.php#L102

### PR DESCRIPTION
**Pull request by zanderwar**
Closes #6192

Let me know if you would prefer a scope other than `public` (as `Mock_Core_URI` needs access to it, I'm assuming `public` is fine.)

### CODE REVIEW

**Comment by ubeljan** [comment]
I think a better way is to implement #[\AllowDynamicProperties]
Shorter and easier.
I give you my changes.


/system/core/URI.php

    #[\AllowDynamicProperties]

    class CI_URI {
    
    
/system/core/Router.php    

    #[\AllowDynamicProperties]

    class CI_Router {
    
    
/system/core/Loader.php   

    #[\AllowDynamicProperties]
    
    class CI_Loader {
    
    
/system/core/Controller.php      
    
    #[\AllowDynamicProperties]

    class CI_Controller {     
    
    
/system/core/DB_driver.php    

    #[\AllowDynamicProperties]

    abstract class CI_DB_driver {

**Comment by zanderwar** [comment]
> I think a better way is to implement #[\AllowDynamicProperties] Shorter and easier. I give you my changes.
> 
> /system/core/URI.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_URI {
> ```
> 
> /system/core/Router.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Router {
> ```
> 
> /system/core/Loader.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Loader {
> ```
> 
> /system/core/Controller.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Controller {     
> ```
> 
> /system/core/DB_driver.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> abstract class CI_DB_driver {
> ```

Thanks, but thats a bit of a hack for lazy people. IDE auto-completion would be more grateful for the explicit declaration of the properties on the class; so will developers...

If that's the route the maintainers want to take then thats up to their discretion, personally never used codeigniter 👍

**Comment by gxgpet** [comment]
#6173

**Comment by behdadpourtavakoli** [comment]
> I think a better way is to implement #[\AllowDynamicProperties] Shorter and easier. I give you my changes.
> 
> /system/core/URI.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_URI {
> ```
> 
> /system/core/Router.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Router {
> ```
> 
> /system/core/Loader.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Loader {
> ```
> 
> /system/core/Controller.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> class CI_Controller {     
> ```
> 
> /system/core/DB_driver.php
> 
> ```
> #[\AllowDynamicProperties]
> 
> abstract class CI_DB_driver {
> ```

Thanks a lot.
It's really working.
I needed to use Codeigniter v3.0.6, but the Codeigniter source normally made some errors, until I found this troubleshoot.
Thanks a lot again.

**Comment by daniyelford** [comment]
right.so you can use Trait without change core like this
we need autoloads like application/core/MY_URI.php

```php

#[\AllowDynamicProperties]
class MY_URI extends CI_URI {}

```

and application/core/MY_Router.php:
```php

#[\AllowDynamicProperties]
class MY_Router extends CI_Router {}

```

and another classes
now codeigniter load perfix MY_ in owner class list
check perfix in your config.php file

```php

$config['subclass_prefix'] = 'MY_';

```

**Pull request closed without merging**
