### PR TITLE
should have news prefix

### PR DESCRIPTION
**Pull request by gavinr**
The sample code should have /news/ prefix so it works correctly.

### CODE REVIEW

**Comment by narfbg** [comment]
1701ad24e7b52df9e0dd51ef7a9a4bb9a99f28bf

**Comment by vlakoff** [comment]
Relative links break so easily when changing site structure, reusing sections...

We should encourage good practices and advise this instead:

    <?php echo site_url('news/'.$news_item['slug']); ?>

(which I'd personally shorten to:)

    <?= url('news/'.$news_item->slug) ?>
    <?= $news_item->url() ?>

**Comment by gavinr** [comment]
@narfbg I see where it was removed, but all I'm saying is that I'm (re-)learning CI and that link does not work for me without `news/` ... maybe I'm missing something.

@vlakoff thanks for that input. Maybe that should be the change instead?

**Comment by narfbg** [comment]
@gavinr More info on the topic: http://forum.codeigniter.com/thread-1217-post-5641.html#pid5641

@vlakoff `site_url()` may do it indeed, good point ... will have to look into it, see if it makes sense within the tutorial (e.g. helpers are not yet explained at that point ...)

**Pull request closed without merging**
