### PR TITLE
Unit test ci input

### PR DESCRIPTION
**Pull request by ahnh**
Input.php " _fetch_from_array" function is fixed and now fully covered by unit test.

### CODE REVIEW

**Comment by narfbg** [comment]
What was broken that is being fixed?

**Comment by ahnh** [comment]
Inside of the for loop, it wasn't checking all the items, if the first item was empty or it's not set.

**Comment by narfbg** [comment]
I don't quite understand what you mean, but it is supposed to stop if it only sees brackets, as there's no sensible way to resolve them ... please revert that and leave only the tests.

Also, your last assertion doesn't represent "empty notation". It may seem as a nitpicky detail, but it's a non-existing value, which isn't the same thing. :)

**Comment by ahnh** [comment]
With the original function, what do you expect the possible keys with the given input 'abc[def]'?

Currently if you give the 'abc[def]' the function will use "abc" as the first key. If the "abc" isn't in the data set, it will return NULL without checking the "def" as another key. This is why I changed so that it can also check the "def" as the key.

**Comment by ahnh** [comment]
I'll revisit it and make another PR later.

**Comment by narfbg** [comment]
It's a recursion of a kind ...

Let's assume we've got a `$this->input->post('abc[def]')` call. In the first iteration, `$value` will be `$_POST` and therefore we'll be checking if `$_POST['abc']` exists - return NULL if it doesn't or do `$value = $_POST['abc']` and go to the next key ... And because of that, `isset($value[$key])` will be in fact looking for `$_POST['abc']['def']`, which is what the whole thing is supposed to do. :)

**Comment by ahnh** [comment]
I now see the point. Thanks Andrey, I'll rework on it.

**Pull request closed without merging**
