### PR TITLE
Updated word_censor() function

### PR DESCRIPTION
**Pull request by achraf52**
Improved and streamlined code workflow, the default character for $replacement should be at the function's argument and no further checking is needed while using the replacement character.

### CODE REVIEW

**Comment by achraf52** [comment]
Travis CI build failed because preg_replace() uses the deprecated /e modifier.
I hope someone can convert it to use preg_replace_callback instead.

**Comment by ivantcholakov** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/4407

**Comment by achraf52** [comment]
Please check what I did in the code before closing the pull request.

**Comment by narfbg** [comment]
Please assume that I check all pull requests before closing them.

**Comment by achraf52** [comment]
So what's the reason why my code changes weren't merged? Please explain in clear words.

**Comment by feryardiant** [comment]
@achraf52 see https://github.com/bcit-ci/CodeIgniter/pull/4418#issuecomment-177415424

**Pull request closed without merging**
