### PR TITLE
allow add of keys with array

### PR DESCRIPTION
**Pull request by avenirer**
This will allow adding multiple keys using array (http://www.codeigniter.com/user_guide/database/forge.html#adding-keys). Only if user wants, he can use the table columns to set a primary key by setting second parameter as TRUE.

### CODE REVIEW

**Comment by narfbg** [comment]
This needs a changelog entry, and if the documentation suggests that it is already supported, then it should be a bugfix one.

**Comment by narfbg** [comment]
Didn't really like the changelog entry (and its place - it should be appended to the list, not prepended), so I cherry-picked your first commit and added the message myself.

Thanks for the effort.

**Comment by avenirer** [comment]
Thank you.

**Comment by narfbg** [comment]
This was reverted because it actually broke functionality ... see the commit I referenced above and issue #4173.

**Pull request closed without merging**
