### PR TITLE
Add Input library functionality.

### PR DESCRIPTION
**Pull request by Chofoteddy**
In order to help enrich the functionality of CodeIgniter, I propose the implementation of the following methods; that will make it easier for the programmer to know the type of method that is used by the client.

```php
if ($this->input->is_post())
{
    // logic of update
}

$this->load->view('/example/form');
```

### CODE REVIEW

**Comment by vardash0131** [comment]
i think it can be useful in any case ...

**Comment by ivantcholakov** [comment]
```php
if ($this->input->method() == 'post')
{
    // logic of update
}
```

**Comment by Chofoteddy** [comment]
@ivantcholakov Yes, it is the current solution, the proposal can be a semantic improvement. In passing, it is useful to reduce the expression used to validate that action.

**Comment by Chofoteddy** [comment]
@ivantcholakov @narfbg 

The most powerful frameworks have semantic improvement methods that are very helpful.

Does not CodeIgniter pretend to be like that? (helpful)

> CodeIgniter is a powerful PHP framework with a very small footprint, built for developers who need a simple and elegant toolkit to create full-featured web applications.

Reference:
- https://api.symfony.com/master/Symfony/Component/HttpFoundation/Request.html#method_isMethod
- https://www.yiiframework.com/doc/api/2.0/yii-web-request#getIsPost()-detail

**Pull request closed without merging**
