### PR TITLE
more correct validation of session id

### PR DESCRIPTION
**Pull request by fiblan**
Signed-off-by: Fabio Sfuncia <fiblan@tooware.com>

### CODE REVIEW

**Comment by fiblan** [comment]
View internal php validation:
https://github.com/php/php-src/blob/master/ext/session/session.c#L456

**Comment by narfbg** [comment]
How's that more correct?

**Comment by fiblan** [comment]
Actual regexp
```
'/^[0-9a-f]{40}$/'
``` 
validate only a possible format, 
the proposed:
```
'/^[-,a-zA-Z0-9]{1,128}$/'
```
is in accordance with https://github.com/php/php-src/blob/master/ext/session/session.c#L456 
and considering the configuration ```session.hash_bits_per_character=6```
http://php.net/manual/en/session.configuration.php#ini.session.hash-bits-per-character

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/Session.php#L317

**Pull request closed without merging**
