### PR TITLE
Hash: processing algorithm name case-insensitively in hash_pbkdf2()

### PR DESCRIPTION
**Pull request by tianhe1986**
Original `hash_pbkdf2()` allows upper-case algorithm name.

### CODE REVIEW

**Comment by narfbg** [comment]
Are you going through every single line of our code?

Not that I don't appreciate your contributions, but if you're going to submit 20 pull requests for one-liners that nobody would ever notice, you might as well submit them all at once.

**Comment by tianhe1986** [comment]
@narfbg OK, I'll submit them at once next time if you accept this way.

I remember that you asked me to commit two changes separately, so I thought maybe I must do like this every time :)

**Comment by narfbg** [comment]
That's the rule in general and I often note newcomers about it as a lot of people try to submit features, bug fixes and styling changes at once.

When you submit tens of patches like this one though, it becomes bureaucracy. :)

**Comment by narfbg** [comment]
Please move the `strtolower()` call inside the `is_array()` check, we don't need that assignment.

**Comment by tianhe1986** [comment]
Oh, I just copy your words and forget to modify it to `in_array()`  :)

**Pull request merged**
