### PR TITLE
Update Input.php

### PR DESCRIPTION
**Pull request by eecjimmy**
where $name is array and  not include 'expire'

### CODE REVIEW

**Comment by narfbg** [comment]
Explain please ... this doesn't seem to make any sense.

**Comment by eecjimmy** [comment]
oh, my english is so poor ^_^

**Comment by eecjimmy** [comment]
if $name is an array but not explain 'expire', and when function argument['expire'] is not set, will can't setcookie success.

**Comment by narfbg** [comment]
Yes it [can](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Input.php#L395).

**Comment by eecjimmy** [comment]
my PHP version is 5.3.29.
when code like below, can set cookie success.
```
setcookie('test','test');
```
but when code like this, set cookie failed.
```
$this->input->set_cookie('test2','test2');
```

**Comment by narfbg** [comment]
It doesn't fail, it deletes the cookie instead.

That's how this method has always worked ... it's not just an alias for `setcookie()`.

**Comment by eecjimmy** [comment]
This may make people for their mistakes, perhaps, we should follow usage.

**Comment by eecjimmy** [comment]
however , tks.

**Pull request closed without merging**
