### PR TITLE
Update welcome_message.php (fix)

### PR DESCRIPTION
**Pull request by ProfNandaa**
This is PR is a build up of #4030, applies the fixes as recommended by @softwarespot:

- Remove the `wrapper div`
- Standardise the color-code casing
- Extra: font-size modification

cc. @narfbg 

screen shot 2017-01-08 at 1 23 33 am

### CODE REVIEW

**Comment by JordanP** [comment]
Could you squash all the commits or at least rework your history ? It currently doesn"t look nice.

**Comment by ProfNandaa** [comment]
@JordanP - I'd tried to maintain the history since that was @DiederikLascaris's work, but sure I can squash them and do a push.

**Comment by ProfNandaa** [comment]
@JordanP - done.

**Comment by ProfNandaa** [comment]
Hi @narfbg, any feedback on this?

**Comment by narfbg** [comment]
You didn't wait for @DiederikLascaris to respond to #4030 before opening this - this is why I've largely ignored it.

But also, you've made way more changes than what had to be done.

**Comment by ProfNandaa** [comment]
@narfbg -- no worries, [I said if Diederik responds on time, just close this one](https://github.com/bcit-ci/CodeIgniter/pull/4030#issuecomment-271114129). Let me know what needs to be excluded and I'll remove them.

**Comment by DiederikLascaris** [comment]
Hi guys,
Sorry for the late reaction. I'll update the original request later this weekend.

**Comment by ProfNandaa** [comment]
@DiederikLascaris &mdash; sounds good, I'll therefore close this one.

**Pull request closed without merging**
