### PR TITLE
Remove closing blocks at end of PHP files

### PR DESCRIPTION
**Pull request by vlakoff**
Here are my changes for addressing #3476. Should supersede #3488.

### CODE REVIEW

**Comment by narfbg** [comment]
I don't like commenting on commits ... the conversations get lost easily. So, continuing here from https://github.com/bcit-ci/CodeIgniter/commit/4606ac3c6b3c512f10820c6568c1080ec08ca182#commitcomment-9363377

I thought you proposed no comments at all at EOF?

**Comment by Razican** [comment]
The question is about the docs. I think that with putting the code with no EOF comments would be better than putting the EOF comment only in the docs.

**Comment by narfbg** [comment]
@Razican I don't really understand your last comment ...

Anyway, it looks ambigous in the docs and I don't personally see a way of making it otherwise, so I'd rather just remove that particular 'incorrect vs. correct' example and leave it just to wording.

Btw, I'd also change the wording a bit ...

Before:

    For this reason, all PHP files should **OMIT** the closing PHP tag. You should also put one empty line at the bottom of the file.

After:

    For this reason, all PHP files MUST OMIT the closing PHP tag and end with a single empty line instead.

I don't care much about the styling, which is why I didn't bold anything myself - your call on that.

**Comment by Razican** [comment]
What I meant was that the EOF comment in the docs is only for clarifying purposes.

**Comment by vlakoff** [comment]
Agree with your comments, PR updated.

**Comment by ivantcholakov** [comment]
Is such end-of-file cleaning to be applied on codeigniter3-translations project?

**Comment by narfbg** [comment]
You can raise that as an issue there, or better yet - submit a pull request. I don't see a reason not to, but it's a separate repository, which I'm not involved with.

**Pull request merged**
