### PR TITLE
Fixed deprecation errors for php >=5.6

### PR DESCRIPTION
**Pull request by SCIF**
Guys, it's very bad idea to use error shut up operator if we can do that properly.

### CODE REVIEW

**Comment by narfbg** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/3549#issuecomment-297683685

**Comment by SCIF** [comment]
@narfbg , [your comment](https://github.com/bcit-ci/CodeIgniter/issues/3549#issuecomment-297683685) does not cover `internal_encoding` directive which has more priority rather than `default_charset`. Check my code please — it sets correct directives and does not trigger ANY errors. Behavior is the same as expected.

**Comment by narfbg** [comment]
I did check your code and it is incorrect in at least two different ways.

There's no `php.internal_encoding` directive. It is `iconv.internal_encoding` and `mbstring.internal_encoding` that have higher priority over `default_charset`.

**Comment by SCIF** [comment]
@narfbg Heh. I doubt that you understand what we talking about.
1) http://php.net/manual/en/ini.core.php#ini.internal-encoding
2) It does not makes sense to set `iconv.internal_encoding` because it falls back to `default_charset`

**Comment by SCIF** [comment]
@narfbg , hm, it looks like your code had typo and I copied it. Anyway, reason 2 is still actual and makes sense. According to docs, it makes sense just leave setting `default_charset` for php>=5.6 because `default_charset` and `*.internal_encoding` has the same value.

**Comment by narfbg** [comment]
Yea, sure ... First I didn't check your code, and now I don't even understand what we're talking about.  

1. You're linking to an obscure description of `internal_encoding` (which says nothing about precedence), yet your code sets `php.internal_encoding`. Note the `php.` prefix; no such directive exists. No, my code didn't have a typo; **you** put this prefix in there.
2. The point is to *override* existing INI directives and NOT to rely on fallbacks. [My comment on #3549](https://github.com/bcit-ci/CodeIgniter/issues/3549#issuecomment-297683685) explains this. Who didn't read or understand something here?

`internal_encoding` does have a higher precedence over `default_charset` - I'll give you that. However, `iconv.internal_encoding` and `mbstring.internal_encoding` *still* have higher precedence even over `internal_encoding`.  
The entire precedency "chain" is shown here: https://github.com/php/php-src/blob/PHP-7.1.5/php.ini-production#L968

Did you seriously think we're happy with the error suppression? No, we *have* to use it in order to fix broken configurations.

P.S.: The docs on this are bad, indeed.

**Comment by SCIF** [comment]
1. Are you [kidding](https://github.com/bcit-ci/CodeIgniter/pull/5115/files#diff-2b5d1b5e02bd017451cd950f04723379L227)??
2. Yes, I read your comment and understand it fully, but that can happen only in one case — admin/developer overrides default value of `*.internal_encoding`. And that is *deliberate choice* of user then. So would you like force setting other value and break user choice?

**Comment by narfbg** [comment]
1. Fair enough, my bad. If you want to fix *that*, I'll be happy to merge your PR.
2. A lot to say about this ...

   - You're *assuming* it's a deliberate choice; this is far from guaranteed.
     - Left-over settings after upgrades.
     - Limited access environments are not rare, to say the least, and it is very common that devs don't have access to php.ini.
   - Even if intentional, php.ini directives apply to *PHP in general*; it is far from certain that the goal is to override CI in particular.
   - Deliberate choice doesn't equal correct choice.
   - Our users actually expect `config.php` to be all they need to configure.
   - And yes, I do like enforcement. :)

**Comment by SCIF** [comment]
@narfbg ,
1. Yeah, I will fix it.
2. It's pretty bad approach — user supposed to be an idiot and you know better what he want :(
Ok, in this case I suggest next logic — check if some of `*.internal_encoding` directives setted and if so, force it with `ini_set()`. If null — just set `internal_encoding` and that will allow system to bootstrap without  suppresing  if everything configured correct.

Are you happy with that?

**Comment by narfbg** [comment]
What would be the point of that? More code and overhead for zero benefit.

**Comment by SCIF** [comment]
@narfbg , zero suppressed errors will be triggered if php server configured properly.

**Comment by narfbg** [comment]
Sure, but how does that benefit anybody?

Error suppression is bad because it hides errors that you *should* care about. This isn't the case here.

**Comment by SCIF** [comment]
I care about deprecation errors and my application does not suppres any errors in dev mode.

**Comment by narfbg** [comment]
Do you *receive* the deprecation errors? Unless so, you care about a problem that doesn't exist.

**Comment by SCIF** [comment]
Yes, I receive.

**Comment by narfbg** [comment]
Where? How?

**Comment by SCIF** [comment]
My debug panel show me all errors, including suppressed. Also, your current approach is bad because of next case: user has a correct setup and didn't use `*.internal_encoding` but he require to set custom encoding in his code. He will be forced to suppress errors and set deprecated values in his code, because CI setted it.

**Comment by narfbg** [comment]
> My debug panel shows me all errors, including suppressed.

A debugger could even show you the exact memory blocks allocated by PHP while running your app. Using this as an argument isn't any better than "but I know the code is there".  

A valid issue would be if it appears in any output produced by the application itself, or in the error logs.

> Also, your current approach is bad because of next case: user has a correct setup and didn't use `*.internal_encoding` but he require to set custom encoding in his code. He will be forced to suppress errors and set deprecated values in his code, because CI setted it.

1. This is a bullshit scenario.
2. No, the user wouldn't have to change the INI settings at runtime. All mbstring and iconv functions accept charset as a parameter.
3. You're way too eager to make up excuses for telling us that we're "bad" and be snarky in general. This won't help you convince me in *anything*.

**Comment by SCIF** [comment]
Yeah, only [freaks care](http://symfony.com/blog/new-in-symfony-3-3-persisted-deprecation-logs) about deprecations. You are on right track, go ahead. I will not spend my, and your, time on debugging and improving CI anymore.

**Pull request closed without merging**
