### PR TITLE
Reduce once $config['query_toggle_count'] checking

### PR DESCRIPTION
**Pull request by bjjay**
This checking can be done by calling set_sections method when initialize profiler .

### CODE REVIEW

**Comment by narfbg** [comment]
You might as well remove the foreach loop too then.

**Comment by bjjay** [comment]
This key isn't included in the array.

**Comment by narfbg** [comment]
What has that got to do with removing the loop?

**Comment by bjjay** [comment]
The loop is for $_available_sections, and the key isn't in $_available_sections but can be in $config. What's wrong with this?

**Comment by narfbg** [comment]
I'm not saying there's anything wrong with this - it's completely fine. I'm saying you can *remove* the loop, because it's also handled by `set_sections()`.

**Comment by bjjay** [comment]
The loop is setting default sections to display.

**Comment by narfbg** [comment]
Head -> desk.

**Comment by bjjay** [comment]
If the sections are defined in config file, this loop can be removed.

**Pull request merged**
