### PR TITLE
updates version of sphinx to 1.6.3 for easyinstall command in step 2 …

### PR DESCRIPTION
**Pull request by ryanbriscall**
…of user_guide_src/README.  Related to issue: https://github.com/sphinx-doc/sphinx/issues/3838

### CODE REVIEW

**Comment by ryanbriscall** [comment]
Related to issue: https://github.com/sphinx-doc/sphinx/issues/3838

**Comment by jim-parry** [comment]
Confirmed that this will work. It is a bit of a pain in CentOS/RHEL, but doable.
The user guide readme should also note that python 2.7 is a requirement for that too, not just a suggestion.

**Comment by narfbg** [comment]
sphinxcontrib-phpdomain may be the bigger issue here.

**Comment by jim-parry** [comment]
What is the problem with sphinxcontrib-phpdomain?
I did an altinstall of python 2.7, and then installed sphinx and sphinxcontrib-phpdomain with that.
Rebuilding the user guide seemed to work, with a warning about "RemovedInSphinx17Warning".
Building the user guide completely gave pages of warnings about " WARNING: Pygments lexer name 'ci' is not known".
The user guide appeared to build properly in spite of these.

**Comment by narfbg** [comment]
I'm not saying that there's certainly a problem with it. I just remember it was hard to find a working version last time I setup things.

**Comment by jim-parry** [comment]
ok - python2.7, sphinx 1.6.3, *and* remembering to install ci_lexer (I missed this before) gives as clean a build as can be expected. Remaining errors are in our user guide source.
I am happy with this PR.

**Comment by narfbg** [comment]
These appear when building against the develop branch, and the sources seem correct:

    /home/narf/citest/user_guide_src/source/database/query_builder.rst:122: WARNING: Could not lex literal_block as "ci". Highlighting skipped.
    /home/narf/citest/user_guide_src/source/general/urls.rst:49: WARNING: Could not lex literal_block as "ci". Highlighting skipped.
    /home/narf/citest/user_guide_src/source/libraries/input.rst:204: WARNING: Could not lex literal_block as "ci". Highlighting skipped.
    /home/narf/citest/user_guide_src/source/libraries/loader.rst:126: WARNING: Could not lex literal_block as "ci". Highlighting skipped.

**Pull request merged**
