### PR TITLE
Reloadconfig hook

### PR DESCRIPTION
**Pull request by nispa**
Hello, 
can you have a look to my patch... ;)
I extended the "hooks" so you can add every configuration path, and added reload_config (to call when you add a configuration path).
Thanks for your work and your time!
Nico.

### CODE REVIEW

**Comment by narfbg** [comment]
Hooks are feature-agnostic, i.e. what happens inside them is not our business - the user decides that.

Also, your second commit goes against our [styleguide](https://codeigniter.com/userguide3/general/styleguide.html), and altering every single non-comment line makes the combined patch very hard to review - don't do that in the future.

**Comment by nispa** [comment]
Ok, sorry... :) 
my IDE realigned every single line...

**Comment by nispa** [comment]
...the correct code is here: https://github.com/bcit-ci/CodeIgniter/pull/4759/commits/d9ec8a7c99904b12d269da76c060b5b7b387fcaf
;)

**Comment by narfbg** [comment]
I did look at the individual commits.

**Pull request closed without merging**
