### PR TITLE
FTP library list_files

### PR DESCRIPTION
**Pull request by bQt31**
How about permitting the developer to get a more detailed list of files with the `ftp_rawlist` function?

### CODE REVIEW

**Comment by narfbg** [comment]
You'll have to add documentation as well.

Also, it's a tiny patch, but can still be improved for better readability.

**Comment by gxgpet** [comment]
@bQt31 Documentation for Ftp.php is located at `/user_guide_src/source/libraries/ftp.rst`.

**Comment by DavisMiculis** [comment]
How about shorter way?
```
return $detailed ? ftp_rawlist($this->conn_id, $path) : ftp_nlist($this->conn_id, $path);
```

**Comment by Calico90** [comment]
+1

**Comment by narfbg** [comment]
@Calico90 GitHub has reacting built-in, so you can give a thumbs-up on the OP's post. Comments saying "+1" are just noise.

@bQt31 You still haven't added a docs patch, and not following our [styleguide](https://codeigniter.com/userguide3/general/styleguide.html).

**Pull request closed without merging**
