### PR TITLE
docs: explicitly state that this is for CI3

### PR DESCRIPTION
**Pull request by kenjis**
It is not noted here that this repository is version 3 and that the latest version is 4.
The latest version is not known to those who come to this repository by search. See https://github.com/bcit-ci/CodeIgniter/issues/6241#issuecomment-1937548732

This PR makes it clear.

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Review by tbreuss — APPROVED** [review]
Looks good to me, thanks.

**Review by lonnieezell — APPROVED** [review]

**Comment by kenjis** [comment]
@gxgpet Could you merge?

**Comment by kenjis** [comment]
Can someone merge?

**Comment by lonnieezell** [comment]
@kenjis done

**Pull request merged**
