### PR TITLE
2.2 stable

### PR DESCRIPTION
**Pull request by DevotionGeo**

### CODE REVIEW

**Comment by taggedboy** [comment]
I think this one is the addition of nice validation rules. Even I needed alpha with spaces months ago.

**Comment by DevotionGeo** [comment]
Dear Andrey Andreev, I think the form validation rules like alpha_spaces and alpha_numeric_spaces are needed.
Every time I need to add a custom validation rule like this.

public function fullname_check($str) {
    if (! preg_match("/^([a-z0-9 ])+$/i", $str)) {
        $this->form_validation->set_message('fullname_check', 'The %s field can only be alpha numeric');
        return FALSE;
    } else {
        return TRUE;
    }


This merge will solve the problem.

**Comment by ZombieProtectionAgency** [comment]
@DevotionGeo I am pretty sure narfbg has said that he wont be merging any non-security patches into CI 2 anymore

**Comment by DevotionGeo** [comment]
Oh ! That's great, it means they are encouraging the use of v 3. Thank You Andrey Andreev for the great work !

**Pull request closed without merging**
