### PR TITLE
Update Pagination.php

### PR DESCRIPTION
**Pull request by acclea**
go to a page

### CODE REVIEW

**Comment by narfbg** [comment]
Eh?

**Comment by acclea** [comment]
@elminson 
1,2)I meet a need to jump to the specified page, for example, there are 100 pages, but can not be displayed, I want to jump to a page, i need to click on the next page / last page.
3) That's it.

**Comment by narfbg** [comment]
The usability problem that you're trying to solve with this is what search bars are made for ...

**Comment by AllenChong** [comment]
pull request

**Pull request closed without merging**
