### PR TITLE
system/core/Common.php, function html_escape

### PR DESCRIPTION
**Pull request by logsdon**
Fix: array_fill() throws an error if count($var) is 0
Signed-off-by: Joshua Logsdon <logsdon.joshua@gmail.com>

### CODE REVIEW

**Comment by narfbg** [comment]
I wouldn't put this inside the `if (is_array($var))` block ... any empty value (strings, integers, etc. included) should be immediately returned if we're going to check if anything's empty. But the obvious question is - why are you passing an empty array to `html_escape()` in the first place?

Also, no spaces around the empty() call please.

**Comment by logsdon** [comment]
This wasn't an issue in CI 2.x for me but the new CI 3.x $html_escape param for set_value() is what lead me to this. If I'm expecting set_value() to return an array and I pass the $default param as array() is when it's happening to me, because it gets passed on to html_escape.

I was doing empty($var) really to do a count($var) == 0 check, but it makes sense like you said to check $var at the top.

Worth fixing and pull requesting again?

**Comment by narfbg** [comment]
Just commit the changes and push them to the same branch, no need for a separate pull request.

**Comment by logsdon** [comment]
Excellent. That should be updated now. Thank you.

**Comment by narfbg** [comment]
Um ... could you also remove the comment line please. It's quite obvious what's going on.

**Comment by logsdon** [comment]
Good to go.

**Pull request merged**
