### PR TITLE
Add new date validation rules to form_validation library

### PR DESCRIPTION
**Pull request by ChadTiffin**
This PR includes 3 new Form_validation rules:

- valid_date
- date_is_past
- date_is_future

Rule reference in docs are updated as well

### CODE REVIEW

**Comment by jim-parry** [comment]
Picky, but in the docs wouldn't the description for valid_past and valid_future say "invalid OR is in the future/past"?

**Comment by ChadTiffin** [comment]
Yeah valid point, I'll correct it in the morning

**Comment by ChadTiffin** [comment]
Wording is fixed

**Comment by narfbg** [comment]
Duplicate of #4346.

**Pull request closed without merging**
