### PR TITLE
quick fix error insert_batch using PHP7

### PR DESCRIPTION
**Pull request by iam-adty**
add reset($key) on line 1548

### CODE REVIEW

**Comment by narfbg** [comment]
And what does that fix?

**Comment by iam-adty** [comment]
to fix this issue [https://github.com/bcit-ci/CodeIgniter/issues/4804](url)

**Comment by narfbg** [comment]
Well ... in the future, please don't open separate issue and pull request.

I'm sure you can see how that's problematic - you have a pull request here with no description or context at all, and thus - no way of knowing why you want this change. And even if you did initially link to #4804, we'd still have to click around between two separate issues to understand what's going on.

**Comment by pepegarciag** [comment]
Well i just going to leave here my comment instead in the related issue(#4804).

I had the same issue working with PHP 7.0.8, if I change to PHP 5.5.26 I have no errors.

If I create a static array like the one I'm using there is no problem (my array was created dinamically) so instead of changing CI core, i just reset my array pointer on my code and all the errors went out.

**Comment by iam-adty** [comment]
@pepegarciag Yap. I just reset all of my arrays before throwing them to every functions of CI.

Case closed. Thanks everyone.

**Pull request closed without merging**
