### PR TITLE
Enable sub-directory for default_controller

### PR DESCRIPTION
**Pull request by bcphung**
Not sure if a bug or it means to be, well, following the general changelog for CI 3, multiple levels of controller directory is on, and one piece still missing is `$route['default_controller']` out of sight.

Let's take an example:
`$route['default_controller'] = 'backend/dashboard';` will result that _backend_ is the controller (_Backend.php_) instead of _Dashboard.php_
So, the new method will working on purpose.

### CODE REVIEW

**Comment by narfbg** [comment]
The bug is that you were ever able to put a directory in there, not that you can't do it now.

**Comment by bcphung** [comment]
With the release of rc3, I faced a problem:
`$route['default_controller'] = 'directory/controller';` this always parsed that `directory` is the controller here.

With this commit, I can do the magic.

**Comment by narfbg** [comment]
I know what your commit does, but you're not supposed to do that "magic".

Again, that you were ever able to use it as directory/controller was due to a bug, and it has never been a fature. 'default_controller' was always a controller/method pair.

**Comment by bcphung** [comment]
Then, index.php is the place that I have to come for.

Well, I will keep this for myself.

Thanks.

**Comment by kuez** [comment]
I need to reo open this bug because i notice that the marge of code is not correct, i checked the file /system/core/Router.php with the commit ba71bee241065782d312afeecba1f4c2981bc213  and is not the same :( , i dowloaded CI v3.1.8 from github. Thanks

image

**Comment by bcphung** [comment]
I'm sorry @kuez, you are looking at a closed PR, which was not approved.
If you want patching around for your own usage, just copy-n-paste as of the diff.

**Pull request closed without merging**
