### PR TITLE
Custom Tab Width

### PR DESCRIPTION
**Pull request by CodeIgniter**

### CODE REVIEW

**Comment by narfbg** [comment]
What does this do and why do we need it?

**Comment by CodeIgniter** [comment]
Because the current tab width is 8 spaces, it is possible to customize the better.

**Comment by narfbg** [comment]
You're saying nothing with that ...

**Comment by CodeIgniter** [comment]
OK. But CodeIgniter 3.0 Chinese user guide change the width of the 4 spaces.
It is a small improvement to the user guide project.

**Comment by narfbg** [comment]
There is no official Chinese user guide and nothing in the Sphinx config is intended for external use. 

And I still don't understand what does this actually improve ... please explain it in detail.

**Pull request closed without merging**
