### PR TITLE
foreign key constraint method

### PR DESCRIPTION
**Pull request by rejoan**
Hi,
Please check this commit. 
https://github.com/rejoan/CodeIgniter/commit/a8669cd09521fb78ae39bcae7923f517f0618a22

I have successfully developed a method add_key_foreign() to add foreign key constraint in existing table. Its working nicely & tested.

ISSUE details (Feature Request)
https://github.com/bcit-ci/CodeIgniter/issues/1762

Thanks

### CODE REVIEW

**Comment by EpicKris** [comment]
@narfbg Is this available in CodeIgniter 3?

**Comment by narfbg** [comment]
Is it in the changelog?

**Comment by rejoan** [comment]
@narfbg Please add this commit to master. Its working. Tested. I can complete this method for postgres too, even documentation if ask.

**Comment by jim-parry** [comment]
@rejoan You are trying to merge your *develop* into our *master*??
With commits from a bunch of other people??
You have your bases wrong, and I suspect there might be only 1 of the 31 changed files that might be relevant. I suggest rethinking your PR!

**Pull request closed without merging**
