### PR TITLE
update Migration Class Reference 

### PR DESCRIPTION
**Pull request by ftwbzhao**
http://www.codeigniter.com/userguide3/libraries/migration.html#class-reference

### CODE REVIEW

**Comment by ftwbzhao** [comment]
When ``$target_version`` == ``$current_version``

Run
 ```php
var_dump($this->migration->version(5));
```

Expected

```php
string(3) "005"
```

Actual
```php
int(5)
```

**Comment by ftwbzhao** [comment]
Class reference is ambiguity.

### userguide

---

http://www.codeigniter.com/userguide3/libraries/migration.html#class-reference

### code

---

```php
 * @return	mixed	TRUE if already latest, FALSE if failed, string if upgraded
```

**Comment by narfbg** [comment]
Sorry, but your comments are way more ambiguous ... I understand that you barely know English, but it doesn't seem like you're even trying. Even if there is an issue here, I'd have to go through all of it on my own to figure out what it is.

**Comment by ftwbzhao** [comment]
just change 'Class reference'

**Comment by narfbg** [comment]
... that's the kind of comment that says literally nothing.

**Comment by ftwbzhao** [comment]
Sorry, I thought you knew all about.

now, You just gotta tell me

function ``version`` return type is what? 

### In UserGuide Says
---
 TRUE if no migrations are found, current version string on success, FALSE on failure


### In Code Says 
---
 TRUE if already latest, FALSE if failed, string if upgraded

**Comment by ftwbzhao** [comment]
still ambiguous? If you do not understand, please tell me.

:rose

**Pull request closed without merging**
