### PR TITLE
use = instead of +=

### PR DESCRIPTION
**Pull request by ftwbzhao**

### CODE REVIEW

**Comment by narfbg** [comment]
What's the point of this change? "is not rigorous" means nothing ...

**Comment by ftwbzhao** [comment]
@narfbg 

```php
$this->cache->redis->save('zero', 0);
$this->cache->redis->get('zero'); // string(1) "0"

//now
$this->cache->redis->get_metadata('zero'); // return FALSE

//In fact
$this->cache->redis->get_metadata('zero'); // return  string(1) "0"
```

**Comment by narfbg** [comment]
And what has that got to do with configuration?

**Comment by ftwbzhao** [comment]
Two Commit Tow Things
> First
**use = instead of +=**

---

> Second
**[fix] redis get_metadata**

**Comment by narfbg** [comment]
Look, I am not blind ... I see that there are two commits, that's not what I'm asking.

'use = instead of +=' doesn't explain **why** you want to use = instead of +=. Please be descriptive.

**Comment by ftwbzhao** [comment]
$config is empty array (: Why Use += ?

**Comment by narfbg** [comment]
Good point, but next time - explain that.

Remove the changelog entry, it's in the wrong place and it says nothing.

**Comment by ftwbzhao** [comment]
Just Doing Now..

**Comment by narfbg** [comment]
*Remove* it, don't change it.

**Comment by ftwbzhao** [comment]
OK

**Comment by narfbg** [comment]
Just **remove the changelog entry**!

**Comment by ftwbzhao** [comment]
OK Now!

**Pull request merged**
