### PR TITLE
fix php 8.0 test

### PR DESCRIPTION
**Pull request by sapics**
This pr replaces travis-ci to github actions for php8.0 tests.

### CODE REVIEW

**Comment by gxgpet** [comment]
I can see that, if you visit a Travis build page, you can see the following notice:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

So it looks like the migration will be done automatically upon shutdown of the old domain?

**Comment by sapics** [comment]
It might be done automatically, but I dont know ;)
Anyway, I think that github actions is better as ci for github repository.

**Comment by philsturgeon** [comment]
Let's merge this one if conflicts can be resolved, as CI4 are using Github Actions: https://github.com/codeigniter4/CodeIgniter4/actions?query=workflow%3A%22PHPUnit%22

Alternatively you could merge my PR which includes this, has no conflicts, and has a few more fixes.

**Comment by narfbg** [comment]
Will cover this through #6074.

**Comment by narfbg** [comment]
Hey, just wanted to say thanks for this one. Much more had to be done, but the groundwork you did was a blessing. Cheers!

**Pull request closed without merging**
