### PR TITLE
Feature/parser driver - Issue #217 Parser becomes a driver

### PR DESCRIPTION
**Pull request by ragboyjr**
Hola brochachos! If this meets CI specs, then we just need to update the userguide src, and we be good.

RJ

### CODE REVIEW

**Comment by kabirpust** [comment]
When CodeIgniter alpha_numeric is used to validated a user name like kabir12 or kabir_sd
then if I put like 123 then It takes my input because alpha_numeric try alpha or numeric.

So I hope codeigniter v3 will be added to validated a good scope to validated a user name so that the user can not put down 123 but he can kabir123.

**Comment by jim-parry** [comment]
@kabirpust What does your Feb 24 comment have to do with a parser becoming a driver?

**Comment by kabirpust** [comment]
@jim-parry, Sorry sir, I am not clear your question.

**Comment by jim-parry** [comment]
@kabirpust your comment sounds like you are requesting some new validation feature in codeigniter, which appears to have nothing to do with this PR. what does alpha_numeric or validation have to do with a parser or a driver?

**Comment by dmyers2004** [comment]
I saw this request again and did a little thinking. How would a end user use a "module" or "package" (libraries, modules, and VIEWS which I will just call a "package" in the rest of the comment) from another  user IF this was pluggable and the user that created package foo used parser A while package bar used parser B? 

Sure the pluggable driver would use a "interface" of sorts to make sure the driver implemented the correct methods like any other driver. That's not the issue.

The issue is what happens when the tags and syntax that each driver processes in the "view" string sent in are completely different? Worse when certain features aren't in parser A which are in parser B? As a end user to use package foo and package bar in your application you would need to some how use "both" parsers. Of course the package creator could just use the CI parser but again maybe in my program I am plugging in parser C. The system would need to support multiple parsers at the same time? Maybe like what was done for caching? 

http://www.codeigniter.com/user_guide/libraries/caching.html?highlight=cache#redis-caching

ie specific a specific parser library.

Something like:

$this->parser->ci->process($view,$data); /* built in ci parser */
$this->parser->twiggy->process($view,$data); /* one called twiggy */
$this->parser->process($view,$data); /* default */

Then a "package" could use a specific one regardless of what else is loaded.

**Comment by narfbg** [comment]
Even if we were to merge something like this, it'd need to be rebased, so closing.

#217 is still open as the feature request.

**Pull request closed without merging**
