### PR TITLE
Fixed array parsing

### PR DESCRIPTION
**Pull request by Arthom**
Example data:
	$data = array('testing' => 'testingvalue', 'testingarray' => array('res1' => 'res1', 'res2' => 'res2'));

Example page with text:
	{testing}<br /><br />

	{testingarray}
		{res1}<br />
		{res2}
	{/testingarray}

And result:
	testingvalue

	res1
	res2

You can try that :)

### CODE REVIEW

**Comment by narfbg** [comment]
I don't understand the problem you're trying to fix, please elaborate.

**Comment by Arthom** [comment]
I had a problem with array parsing (ex. testingarray).
$data = array('testing' => 'testingvalue', 'testingarray' => array('res1' => 'res1', 'res2' => 'res2'));

It threw me error.
screenshot from 2016-10-26 17-49-01

Line 258:
foreach ($row as $key => $val)

**Comment by narfbg** [comment]
You're just not doing it right ... the correct usage is shown [here](https://codeigniter.com/userguide3/libraries/parser.html#variable-pairs).

**Comment by Arthom** [comment]
But it's good idea to parse this method of array :)

**Comment by narfbg** [comment]
You think it's a good idea, I don't necessarily do.
But I think we can both agree on what's bad - breaking existing functionality, and your patch does that.

**Comment by Arthom** [comment]
But when you want to parse variable with array, you can't do that. You need to add extra array to foreach that object.

**Pull request closed without merging**
