### PR TITLE
Update CodeIgniter.php

### PR DESCRIPTION
**Pull request by piece601**
I think defult vendor directory in project root directory.

### CODE REVIEW

**Comment by narfbg** [comment]
... if that is your project root. You like it that way, others don't.

**Comment by piece601** [comment]
but default composer.json in project root directory.

**Comment by narfbg** [comment]
Yes, but that's for CI's own development, and at this time - only for running the test suite.

Otherwise, you can copy the application/ dir for multiple projects and manage different dependencies for them via composer, while still using the same system/ dir.

**Comment by davidgv88** [comment]
The solution:

In application/config/config.php
$config['composer_autoload'] = FCPATH.'vendor/autoload.php';

**Comment by piece601** [comment]
@davidgv88 Thanks.

It's good idea~

**Comment by davidgv88** [comment]
Yesterday I wrote the same:
http://forum.codeigniter.com/thread-1429.html

**Comment by narfbg** [comment]
Please keep it on the forums ... GitHub is NOT the place to ask or search for tips.

**Comment by arikardnoir** [comment]
Im installing composer in Codeigniter and the files are going to dir "libraries", it's not creating the dir "vendor" in my app. When Im creating manual, and then make update of composer, he's creating files again in libraries.

**Pull request closed without merging**
