### PR TITLE
addition of config property

### PR DESCRIPTION
**Pull request by divineAzrael**
property config was not defined

### CODE REVIEW

**Comment by bunglegrind** [comment]
what does it solve?

**Comment by divineAzrael** [comment]
> what does it solve?

on my develop branch it showed me a list of errors including variables not declared, which lead back to properties not defined, but most likely there is something wrong on my side...

**Comment by bunglegrind** [comment]
You're supposed to open an issue beforehand, or at least explain better why you are submitting a PR

**Comment by divineAzrael** [comment]
I am new to open source and wanted to contribute to CodeIgniter , I did not know it. I'll take it into consideration. Thank you for your support.

**Pull request closed without merging**
