### PR TITLE
Automatically setup base_url

### PR DESCRIPTION
**Pull request by SyedMuradAliShah**
It will set automatically the base_url even if somebody used a folder in localhost or online server.

### CODE REVIEW

**Comment by gxgpet** [comment]
Hi! Could you please explain the issue?

As a side note, CodeIgniter has already `base_url` auto-detection, which should work for local environments as well. The config item `base_url` exists so that you don't rely on this auto-detection mechanism, but rather explicitly set it - even for a `localhost` environment.

**Comment by kenjis** [comment]
This PR introduces Host header injections again.
See https://github.com/bcit-ci/CodeIgniter/commit/0a6b0661305f20ac1fbd219d43f59193bea90d1d

**Comment by SyedMuradAliShah** [comment]
@gxgpet actually without this when you use a Codeigniter inside a directory, the auto-detection mechanism does not work. It detects the HOST_NAME rather than detecting the hostname with directory!
Example: `c:/www/codeigniter-blog`
If `localhost` point to `c:/www` so when we try to access `localhost/codeigniter-blog` codeigniter will detect its `base_url` as `localhost` not with directory which is `codeigniter-blog`

**Comment by SyedMuradAliShah** [comment]
@gxgpet actually without this when you use a Codeigniter inside a directory, the auto-detection mechanism does not work. It detects the HOST_NAME rather than detecting the hostname with directory!
Example: `c:/www/codeigniter-blog`
If `localhost` point to `c:/www` so when we try to access `localhost/codeigniter-blog` codeigniter will detect its `base_url` as `localhost` not with directory which is `codeigniter-blog`

**Comment by SyedMuradAliShah** [comment]
@gxgpet actually without this when you use a Codeigniter inside a directory, the auto-detection mechanism does not work. It detects the HOST_NAME rather than detecting the hostname with directory!
Example: `c:/www/codeigniter-blog`
If `localhost` point to `c:/www` so when we try to access `localhost/codeigniter-blog` codeigniter will detect its `base_url` as `localhost` not with directory which is `codeigniter-blog`

**Comment by SyedMuradAliShah** [comment]
@gxgpet actually without this when you use a Codeigniter inside a directory, the auto-detection mechanism does not work. It detects the HOST_NAME rather than detecting the hostname with directory!
Example: `c:/www/codeigniter-blog`
If `localhost` point to `c:/www` so when we try to access `localhost/codeigniter-blog` codeigniter will detect its `base_url` as `localhost` not with directory which is `codeigniter-blog`

**Comment by SyedMuradAliShah** [comment]
@gxgpet actually without this when you use a Codeigniter inside a directory, the auto-detection mechanism does not work. It detects the HOST_NAME rather than detecting the hostname with directory!
Example: `c:/www/codeigniter-blog`
If `localhost` point to `c:/www` so when we try to access `localhost/codeigniter-blog` codeigniter will detect its `base_url` as `localhost` not with directory which is `codeigniter-blog`

**Comment by narfbg** [comment]
Duplicate of #4361, among many others. You have to configure this by hand - if there was a good way around this, we wouldn't have the config option at all. But there isn't, it's a security sensitive thing as @kenjis pointed out.

**Pull request closed without merging**
