### PR TITLE
Added method to pull config fields out of post data

### PR DESCRIPTION
**Pull request by zoaked**
#2436 - Created a PR for this very useful feature.  In short it only pulls fields out of post data that also have a validation configuration.

### CODE REVIEW

**Comment by jim-parry** [comment]
Good idea. This should also have a changelog entry & update for the user guide, if it is to go ahead.

**Comment by narfbg** [comment]
What if the validated data isn't in `$_POST`?

**Comment by zoaked** [comment]
Is posting code in an issue considered to be providing it to the project?  I did not create this method and am wondering if the original author posting it to the above issue means it is being made available or not?  In my opinion it seems like it does, but I want to also make sure that all your project policies are being followed.

**Comment by narfbg** [comment]
It is, but if you're just submitting a patch that was already provided (in whatever form) by another issue and we haven't applied it, it means we didn't like it in the first place.
One of the reasons why is the questions I asked above, which you didn't answer.

Closing here; you can discuss it in #2436 if you want to.

**Pull request closed without merging**
