### PR TITLE
Change all :doc: links to absolute paths

### PR DESCRIPTION
**Pull request by vlakoff**
This should improve maintainability.

### CODE REVIEW

**Comment by narfbg** [comment]
I don't think that altering the existing content solves anything ... it's a matter of regular error checking.

**Comment by vlakoff** [comment]
It reduces work to do and possibility of errors in case the structure is changed.

**Comment by narfbg** [comment]
How exactly does changing the existing paths do that?

Making a policy to use absolute paths might, but we don't have such and frankly, I don't care enough to implement one. It's documentation, gets updated once in a while and errors appear exactly then (when necessary), it's not production code.

**Comment by vlakoff** [comment]
I've already made all the necessary replacements. Nevertheless, it would introduce a *de facto* standard. Users looking at other parts of the code when making changes. Yep, we could add a "contributing to the documentation" documentation, but don't care much too.

Whatever, just merge it or close it. I'm strongly +1 for the former.

**Comment by vlakoff** [comment]
As you cherry-picked the first commit, can I safely assume you don't plan to merge the main commit?

**Comment by narfbg** [comment]
Well, the first one is a *fix*, so it had to be applied anyway.

I've not yet decided whether to merge it or not, although you know I'm leaning towards the latter ...

**Comment by vlakoff** [comment]
I'm fine if you decide not to merge it; after all, the changes are numerous, which has drawbacks.

Juuust a nitpick, could you please take https://github.com/vlakoff/CodeIgniter/commit/d166c546b5b0b2727f1db02159d64e1cff12d632?

**Comment by narfbg** [comment]
Done.

**Comment by vlakoff** [comment]
Thanks. I'm closing this PR, as the remaining changes most probably won't be taken.

**Pull request closed without merging**
