### PR TITLE
Form Validation: Add native rule valid_mac

### PR DESCRIPTION
**Pull request by yinlianwei**
MAC validation is very common.
php version gt 5.5.0 use  filter_var others use  regular expressions

### CODE REVIEW

**Comment by narfbg** [comment]
I'd argue that it's not *that* common, not in web applications at least, but sure - it'd be handy.

However, it has no place in the `CI_Input` class and should be in `CI_Form_validation` instead. Also, your regular expression doesn't accept the "0123.4567.89ab" format, which *is* accepted by `FILTER_VALIDATE_MAC`. A changelog entry would be necessary as well.

If you don't care about attribution in the git log, I can commit the improved version myself, but otherwise you'd have to address the issues I described above.

**Comment by yinlianwei** [comment]
I think there is a wider web application usage scenario, at least in my projects, often used mac address check. I suggest that the increase of the function, and modify regular expressions.

**Comment by narfbg** [comment]
Arguing about the use cases is a moot point ... ignore that.

I don't understand what is it that you're suggesting ... you didn't really address any of the issues that I mentioned.

**Comment by mixinix** [comment]
How about validation 'alpha_spaces' for user fullname...?
Like 'King Mataram III' not 'King Mataram 3'.

**Comment by narfbg** [comment]
How about not [commenting on issues irrelevant to your question](https://github.com/bcit-ci/CodeIgniter/issues/2436#issuecomment-213282744) and [searching for similar issues first](https://github.com/bcit-ci/CodeIgniter/pull/3815)?

**Comment by mixinix** [comment]
My bad, thanks.

**Pull request closed without merging**
