### PR TITLE
[Bug] Alpine 3.17 and PHP81

### PR DESCRIPTION
**Pull request by mhzawadi**
bug: fix Session wrapper for PHP81

This is a fix for PHP8.1  on Alpine, I have an issue with [InvoicePlane](https://github.com/InvoicePlane/InvoicePlane) that was trowing an error.

[[Bug] Alpine 3.17 and PHP81](https://github.com/InvoicePlane/InvoicePlane/issues/909)

### CODE REVIEW

**Comment by mhzawadi** [comment]
@gxgpet could you have a look at this please?

**Comment by nielsdrost7** [comment]
Guys,
Could you approve this PR and make a new version (tag)?
Our Open Source project relies heavily on CI3 and need this PR for our new version

**Comment by gxgpet** [comment]
Hi!

I'm really having a hard time debugging and identifying the issue on this one... I saw that you posted on the other repo some Docker images containing the potential environment to reproduce the bug, but they don't match (I saw that you are installing PHP 7 on https://github.com/mhzawadi/invoiceplane/blob/master/Dockerfile, for instance). Can you, please, provide an example of the exact Dockerfile that would trigger the error?

**Comment by mhzawadi** [comment]
Hi @gxgpet 

Thanks for having a look at this, the Dockerfile you need is on my dev branch (https://github.com/mhzawadi/invoiceplane/blob/dev/Dockerfile). 

That should give you an example

**Comment by codestellar** [comment]
who will be approving this?

**Comment by mhzawadi** [comment]
Hey, any update on this please?

**Comment by gxgpet** [comment]
By using the latest version of that Dockerfile, the bug doesn't confirm. The bug was either fixed in a more recent release of those distro packages, or either your PHP installation is broken.

To prove this, you can run the following debugging code inside a controller (if you can't get to it, you will have to `require` the classes mentioned in the main `foreach` manually - except `SessionHandlerInterface`, of course - and have the `session` lib disabled):

```php
foreach (array('SessionHandlerInterface', 'CI_SessionWrapper', 'SessionUpdateTimestampHandlerInterface') as $class)
{
	if (!interface_exists($class) && !class_exists($class))
	{
		echo "Class $class not loaded".PHP_EOL;
		continue;
	}

	echo $class.PHP_EOL;
	foreach (get_class_methods($class) as $method)
	{
		echo '::'.$method.PHP_EOL;
		$reflection_method = new ReflectionMethod($class, $method);
		echo 'Return type: '.($reflection_method->hasReturnType() ? (string)$reflection_method->getReturnType() : 'N/A');
		echo PHP_EOL;
		echo 'Tentative Return type: '.($reflection_method->hasTentativeReturnType() ? (string)$reflection_method->getTentativeReturnType() : 'N/A');
		echo PHP_EOL;
		foreach ($reflection_method->getAttributes() as $attribute)
		{
			echo 'Has attribute '.$attribute->getName().PHP_EOL;
		}
		foreach ($reflection_method->getParameters() as $parameter)
		{
			echo 'Parameter $'.$parameter->name.PHP_EOL;
			echo 'Type: '.($parameter->hasType() ? $parameter->getType() : 'N/A').PHP_EOL;
		}
	}
	echo PHP_EOL;
}
```

**Comment by mhzawadi** [comment]
I have just built a new image and pushed to the docker hub, it works without any issue.
Closing this as we dont need it now, thanks for testing

**Pull request closed without merging**
