### PR TITLE
Update CodeIgniter.php

### PR DESCRIPTION
**Pull request by vibbow**
Declare get_instance() return type.

So IDE can detect return type of use get_instance().
Therefore show the correct autocomplete hint.

### CODE REVIEW

**Comment by narfbg** [comment]
You're supposed to replace "object" with "CI_Controller" ...
Also, we use tabs to separate the docblock columns.

**Comment by vibbow** [comment]
Oh, sorry. I suppose to replace object with CI_Controller

**Comment by narfbg** [comment]
So ... are you going to fix that?

**Comment by vibbow** [comment]
Fixed now.

FIrst time learned actually I can modify a pull request :)

**Pull request merged**
