### PR TITLE
Add method field_highlight() to Form Helper

### PR DESCRIPTION
**Pull request by jmb-oliveira**
Add the functionality to easily highlight fields on validation errors

### CODE REVIEW

**Comment by jmb-oliveira** [comment]
Result

capturar

**Comment by narfbg** [comment]
This is doable via a simple ternary condition, we don't need a function for it.

**Comment by jmb-oliveira** [comment]
It's a helper function.

Isn't the same point as using:

```
echo form_input('name', 'value');
```

Instead of
```
<input type="name" value="value" />
```

?

**Comment by narfbg** [comment]
Yes, but just because useless functions have been implemented in the past, that doesn't mean we should continue to do so.

**Comment by jmb-oliveira** [comment]
That's true. I Agree.
Thx for reply.

**Pull request closed without merging**
