### PR TITLE
Activated garbage collection

### PR DESCRIPTION
**Pull request by achraf52**
The garbage collection in the files driver doesn't seem to do it's job, so I'm calling it in the files driver constructor and it seems to work.

### CODE REVIEW

**Comment by narfbg** [comment]
It's not supposed to be run on every request.

**Comment by achraf52** [comment]
So how often and where does the function gets executed? I couldn't find any place in the CodeIgniter system files when it's periodically run.

**Comment by narfbg** [comment]
http://php.net/manual/en/session.configuration.php#ini.session.gc-probability

**Comment by achraf52** [comment]
I know the GC probability, but where it's implemented in CodeIgniter? I want the exact location of the system file that implements the GC probability mechanism to run the aforementioned function.

**Comment by narfbg** [comment]
It's not in CodeIgniter, PHP runs it.

**Comment by achraf52** [comment]
Hum... I tried changing the GC probability values in my PHP.ini file to be run 100% but it doesn't work, I'll do more tests and see if I can get positive results and get GC to run.

**Pull request closed without merging**
