### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by kenjis**
It seems the style like `_application/config/mimes.php*` does not work.
See http://www.codeigniter.com/user_guide/installation/upgrade_300.html#step-3-replace-config-mimes-php

### CODE REVIEW

**Comment by narfbg** [comment]
It's supposed to be italic, not bold ... Please change that to a single asterisk and revert the rest of the changes.

**Comment by kenjis** [comment]
Oh, sorry. I changed to a single asterisk.

And I found that a line break is needed between two file paths:
http://www.codeigniter.com/user_guide/installation/upgrade_300.html#step-5-move-your-log-class-overrides-or-extensions

>  revert the rest of the changes.

Where is wrong?

**Comment by narfbg** [comment]
What's wrong is that you're fixing things that aren't broken ... This is far from your first PR, you should know, at the very least, not to batch multiple changes in a single patch. Here's why:

- While an acceptable change, the lack of a full stop at the end of one sentence isn't necessarily wrong.
- Changing "in order to avoid backwards compatibility" to "for backward compatibility" is good, but I insist on the "s". :)
- Changing "any character" to "any characters" is wrong - "any" for singular, "all" for plural.

If you've found that a linebreak is missing, why are you converting that thing to a list instead of adding the linebreak? While it is obviously a list of a kind, we use different indentation level for bullet-point lists (which this was not intended to be in the first place) and there are at least two similar instances that are now inconsistent with this one (but admittedly also broken, due to missing linebreaks).

It's not that big of a deal - I'm sure you'll now fix these issues. However, your description only says that you're addressing the ``_foo/bar*`` thing and if you really only did that, it would've been merged by now and we wouldn't have to now go back and forth in a conversation that neither of us enjoys.

**Comment by kenjis** [comment]
Okay, I posted another PR #4411 only containing changes formatting of paths.

I close this PR, but I still have something to fix.

> If you've found that a linebreak is missing, why are you converting that thing to a list instead of adding the linebreak?

Because I don't know how to do so. I searched it but I was not able to find how to put linebreak in RST.

> we use different indentation level for bullet-point lists (which this was not intended to be in the first place) and there are at least two similar instances that are now inconsistent with this one

I don't understand the format you want. Do you mean to add one more tab?

**Comment by narfbg** [comment]
>> If you've found that a linebreak is missing, why are you converting that thing to a list instead of adding the linebreak?
>
> Because I don't know how to do so. I searched it but I was not able to find how to put linebreak in RST.

I just found this: http://docutils.sourceforge.net/FAQ.html#how-to-indicate-a-line-break-or-a-significant-newline

But as a general rule, if you don't know how to fix something - just note that it is broken and leave it for someone else to fix. Treat it as real programming code - completely changing it is likely not welcome.

In this particular case, I don't mind switching it to a bullet-point list, but make it consistent and do that for other lists in the document as well. :) Although, changing it to a literal code block may be more readable.

>> we use different indentation level for bullet-point lists (which this was not intended to be in the first place) and there are at least two similar instances that are now inconsistent with this one
>
> I don't understand the format you want. Do you mean to add one more tab?

No ... See "Step 6", which uses a bullet-point list already - the dashes are indented by just 2 spaces further.

**Pull request closed without merging**
