### PR TITLE
Redis performance optimization

### PR DESCRIPTION
**Pull request by gyyinzjut**
Bad performance when there are a great many of redis keys,so serialize all the keys when save keys.

### CODE REVIEW

**Comment by narfbg** [comment]
No, this just moves the performance penalty from Redis to PHP and it impacts non-array values as well.

**Comment by gyyinzjut** [comment]
You mean we should try to limit array values use ?

**Comment by gyyinzjut** [comment]
You mean we should try to limit array values use?

**Comment by narfbg** [comment]
Yes, that's the source of your problem - Redis doesn't have native support for that structure and therefore you cannot expect it to behave well with it.

**Pull request closed without merging**
