### PR TITLE
Common: set_status_header: Remove tabs in $stati

### PR DESCRIPTION
**Pull request by Fieah**
Weird. 
It only visible on Github.

### CODE REVIEW

**Comment by narfbg** [comment]
If you had done that in the previous PR ... ok, but now it's just change for the sake of change.

**Comment by Fieah** [comment]
You should take a look at previous commit on Github web, and compare in your local IDE.
It really not visible on IDE even the diff in Github client for Window.
It's a tab, and that is not OK. 

Don't make any conjectures.

**Comment by narfbg** [comment]
I'm not taking any guesses, nor do I need to - tabs are completely fine.

**Comment by Fieah** [comment]
You should just say that in the first place, and you did guessed.
Just saying. :)

**Comment by narfbg** [comment]
No, I didn't ... The change is very clearly visible in the diff here and I told you that it's an unnecessary change.

**Comment by Fieah** [comment]
You just said if done in previous commit is ok, now this.
Meh, that's fine. Your repo your game. Maybe is the client's fault.  

BTW, kindly check the Memcached PR, thanks.
Have a nice day.

**Comment by narfbg** [comment]
Yes, I said that because your previous PR already modified the exact same lines and that would've been completely fine. I also said this PR is a change for the sake of change - because it doesn't matter if it's a tab or a space here, which I believe was obvious and hence why I didn't explain myself in full detail.

There's no fault and nobody is blamed for nothing.

I also receive emails for every new issue/pull request/comment on the repository, so I'm also aware of your proposed change for the Cache Memcache(d) driver ... I just haven't decided anything about it yet.

Take it easy and stop pushing me, please.

**Comment by Fieah** [comment]
Haha, chill my friend, 
i'm just saying, take your time :)

**Comment by Fieah** [comment]
Hi Andrey, quick question.
I'm working on something in common.php,
is that ok if i merge this changes?

**Comment by narfbg** [comment]
Sure.

**Pull request closed without merging**
